# Generated by Django 4.1.4 on 2022-12-19 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1100, verbose_name='Текст вопроса')),
                ('quess_type', models.SmallIntegerField(choices=[(0, 'Любой правильный ответ'), (1, 'Все правильные ответы')], default=0, verbose_name='Нужно угадать')),
                ('correct_text', models.CharField(max_length=2200, verbose_name='Текст правильного ответа')),
                ('incorrect_text', models.CharField(max_length=2200, verbose_name='Текст неправильного ответа')),
                ('partially_correct_text', models.CharField(max_length=2200, verbose_name='Текст частично правильного ответа')),
                ('sort_order', models.PositiveIntegerField(blank=True, default=0, verbose_name='Порядковый номер вопроса')),
                ('complexity', models.PositiveIntegerField(blank=True, default=1, verbose_name='Сложность вопроса')),
                ('is_start', models.BooleanField(default=False, verbose_name='Стартовый вопрос теста')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, создавший вопрос')),
                ('modified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, отредактировавший вопрос')),
                ('quizz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quizz', verbose_name='Квиз')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'questions',
                'ordering': ['sort_order'],
            },
        ),
    ]
