# Generated by Django 4.1.4 on 2022-12-22 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quess_type',
            new_name='guess_type',
        ),
    ]
