# Generated by Django 4.1.4 on 2023-01-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_rename_quess_type_question_guess_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_start',
            field=models.BooleanField(default=False, verbose_name='Стартовый вопрос квиза'),
        ),
    ]
