# Generated by Django 4.1.4 on 2023-01-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_question_correct_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_text',
            field=models.CharField(blank=True, max_length=2200, verbose_name='Текст правильного ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='incorrect_text',
            field=models.CharField(blank=True, max_length=2200, verbose_name='Текст неправильного ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='partially_correct_text',
            field=models.CharField(blank=True, max_length=2200, verbose_name='Текст частично правильного ответа'),
        ),
    ]
