# Generated by Django 4.1.4 on 2023-04-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_alter_question_correct_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_start',
            field=models.BooleanField(blank=True, default=False, verbose_name='Стартовый вопрос квиза'),
        ),
    ]
