# Generated by Django 4.1.4 on 2023-04-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_alter_question_is_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='complexity',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=1, verbose_name='Сложность вопроса'),
        ),
    ]
