# Generated by Django 4.1.4 on 2022-12-19 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('results', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1100, verbose_name='Текст варианта ответа')),
                ('sort_order', models.PositiveIntegerField(blank=True, default=0, verbose_name='Порядковый номер варианта ответа')),
                ('text_selected', models.TextField(blank=True, verbose_name='Текст после выбора варианта')),
                ('complexity', models.SmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0, verbose_name='Сложность (кол-во баллов выборе)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, создавший вариант ответа')),
                ('modified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, отредактировавший вариант ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='questions.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
                'db_table': 'variants',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='VariantsGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants_graphs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, создавший граф варианта ответа')),
                ('modified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, отредактировавший граф варианта ответа')),
                ('next_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='Следующий вопрос')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='results.result', verbose_name='Результат')),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='variants.variant', verbose_name='Вариант ответа')),
            ],
            options={
                'verbose_name': 'Граф вариантов ответа',
                'verbose_name_plural': 'Графы вариантов ответа',
                'db_table': 'variants_graphs',
            },
        ),
    ]
