# Generated by Django 4.1.4 on 2022-12-21 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('variants', '0003_alter_variantsgraph_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantsgraph',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, создавший граф варианта ответа'),
        ),
    ]
