# Generated by Django 4.1.4 on 2023-04-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0007_alter_variant_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='complexity',
            field=models.IntegerField(default=0, verbose_name='Сложность (кол-во баллов выборе)'),
        ),
    ]
