# Generated by Django 4.1.4 on 2022-12-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizz',
            options={'ordering': ['-created_at'], 'verbose_name': 'Квиз', 'verbose_name_plural': 'Квизы'},
        ),
    ]
