# Generated by Django 4.1.4 on 2023-03-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_alter_quizz_quizz_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='is_auto_activation',
            field=models.BooleanField(default=False, verbose_name='Автоматическая активация'),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='time_type',
            field=models.SmallIntegerField(choices=[(0, 'Без учета времени'), (1, 'Время на вопрос'), (2, 'Время на квиз')], default=0, verbose_name='Ограничениe по времени'),
        ),
    ]
