# Generated by Django 4.1.4 on 2023-01-28 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0008_alter_question_correct_text_and_more'),
        ('quizzes', '0003_alter_quizz_alias_alter_quizz_auto_activation_at_and_more'),
        ('results', '0002_alter_result_scores_range'),
        ('variants', '0006_alter_variant_results'),
        ('attempters', '0003_alter_attempter_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(blank=True, max_length=32, null=True, verbose_name='Уникальный hash попытки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата истечения')),
                ('attempter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attempters.attempter', verbose_name='Участник')),
                ('quizz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quizz', verbose_name='Квиз')),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
                'db_table': 'attempts',
            },
        ),
        migrations.CreateModel(
            name='AttemptQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(blank=True, default=0, verbose_name='Порядковый номер вопроса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_questions', to='attempts.attempt', verbose_name='Попытка')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос в рамках попытки',
                'verbose_name_plural': 'Вопросы в рамках попытки',
                'db_table': 'attempt_questions',
            },
        ),
        migrations.CreateModel(
            name='AttemptResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attempts.attempt', verbose_name='Попытка')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='results.result', verbose_name='Результат попытки')),
            ],
            options={
                'verbose_name': 'Результат попытки',
                'verbose_name_plural': 'Результаты попыток',
                'db_table': 'attempt_results',
                'unique_together': {('attempt', 'result')},
            },
        ),
        migrations.CreateModel(
            name='AttemptQuestionVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('attempt_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attempts.attemptquestion', verbose_name='Вопрос в рамках попытки')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variants.variant', verbose_name='Вариант ответа на вопрос в рамках попытки')),
            ],
            options={
                'verbose_name': 'Вариант ответа в рамках попытки',
                'verbose_name_plural': 'Варианты ответа в рамках попытки',
                'db_table': 'attempt_question_variants',
                'unique_together': {('attempt_question', 'variant')},
            },
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='variants',
            field=models.ManyToManyField(blank=True, through='attempts.AttemptQuestionVariant', to='variants.variant', verbose_name='Варианты ответа'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='results',
            field=models.ManyToManyField(through='attempts.AttemptResult', to='results.result', verbose_name='Результаты попытки'),
        ),
    ]
