# Generated by Django 4.1.4 on 2023-01-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptresult',
            name='correct_answers',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Кол-во ответов для этого результата'),
        ),
        migrations.AddField(
            model_name='attemptresult',
            name='correct_answers_percent',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Процент правильных ответов для этого результата'),
        ),
        migrations.AddField(
            model_name='attemptresult',
            name='percent',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Процент ответов с этим результатов'),
        ),
        migrations.AddField(
            model_name='attemptresult',
            name='score',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Кол-во баллов попытки'),
        ),
        migrations.AddField(
            model_name='attemptresult',
            name='total_percent',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Процент правильных ответов'),
        ),
    ]
