# Generated by Django 4.1.4 on 2023-02-01 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0002_attemptresult_correct_answers_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attemptquestion',
            unique_together={('attempt', 'sort_order')},
        ),
    ]
